# 全局日志级别
LOG_LEVEL = "debug"

# DB 配置，格式为 DB_${NAME}_DSN，内容参考
# https://pkg.go.dev/github.com/lib/pq?tab=doc
# 通过 ${NAME} 可以获取 DB 连接池
# 测试时用的DB
DB_TEST_DSN = "user=wrh dbname=test sslmode=disable"
# 开发或正式用的DB
DB_DEFAULT_DSN = "user=wrh dbname=mydb sslmode=disable"
# 修改DB配置后是否热加载，配合测试使用
HOT_LOAD_DB = true

## DB最大连接数
DB_DEFAULT_MAX_OPEN_CONNS = 20

# MC 配置，格式为 MC_${NAME}_HOSTS = "host1,host2"
# 通过 ${NAME} 可以获取 MC 连接池
MC_DEFAULT_HOSTS = "127.0.0.1:11211"
# 初始连接数
MC_DEFAULT_INIT_CONNS = 1
# 最大空闲连接数，设为峰值并发数
MC_DEFAULT_MAX_IDLE_CONNS = 2

# Redis 配置
REDIS_DEFAULT_HOST = "127.0.0.1:6379"
# 初始连接数
REDIS_DEFAULT_INIT_CONNS = 1
# 最大连接数
REDIS_DEFAULT_MAX_CONNS = 2
